/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 .\models\coffee_shop_cup.glb
Author: David Zerba (https://sketchfab.com/DavidZerba)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-shop-cup-37e6805f2b7a4158a1d61fe75f8e2a33
Title: Coffee Shop Cup
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

const Cup = (props) => {
  const colorBody = props.colorBody;
  const { nodes, materials } = useGLTF('./models/coffee_shop_cup.glb')
  const ColorGreen = new MeshStandardMaterial({color: 0x40E0D0});
  const ColorRed = new MeshStandardMaterial({color: 0xDE3163});
  const ColorBlue = new MeshStandardMaterial({color: 0x6495ED});
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.23}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]} scale={[1.57, 2.44, 1.57]}>
            <mesh geometry={nodes.Object_5.geometry} material={colorBody} position={[0, -0.08, 0]} scale={[0.64, 0.41, 0.64]} />
            <mesh geometry={nodes.Object_7.geometry} material={ColorRed} position={[0, 0.72, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1.04, 0.63, 1.04]} />
            <mesh geometry={nodes.Object_9.geometry} material={ColorBlue} position={[0, -1, 0]} scale={[0.64, 0.41, 0.64]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/coffee_shop_cup.glb')

export default Cup;